CREATE OR REPLACE FILE FORMAT HEALTH_DB.RAW.CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
DATE_FORMAT = 'DD-MM-YYYY';


CREATE OR REPLACE STAGE HEALTH_DB.RAW.HEALTH_STAGE
FILE_FORMAT = HEALTH_DB.RAW.CSV_FORMAT;


LIST @HEALTH_DB.RAW.HEALTH_STAGE;



CREATE OR REPLACE TABLE HEALTH_DB.RAW.MIGRANT_PROFILES (
    migrant_id STRING,
    age INT,
    gender STRING,
    home_state STRING,
    current_state STRING
);

truncate table HEALTH_DB.RAW.MIGRANT_PROFILES;

COPY INTO HEALTH_DB.RAW.MIGRANT_PROFILES
FROM @HEALTH_DB.RAW.HEALTH_STAGE/migrant_profiles.csv
FILE_FORMAT = (FORMAT_NAME = HEALTH_DB.RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';



SELECT * FROM RAW.MIGRANT_PROFILES;

CREATE OR REPLACE TABLE HEALTH_DB.RAW.MEDICAL_VISITS (
    visit_id STRING,
    migrant_id STRING,
    visit_date DATE,
    diagnosis STRING,
    treatment STRING,
    hospital_name STRING
);

truncate table HEALTH_DB.RAW.MEDICAL_VISITS;

COPY INTO HEALTH_DB.RAW.MEDICAL_VISITS
FROM @HEALTH_DB.RAW.HEALTH_STAGE/medical_visits.csv
FILE_FORMAT = (FORMAT_NAME = HEALTH_DB.RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

COPY INTO HEALTH_DB.RAW.MEDICAL_VISITS
FROM @HEALTH_DB.RAW.HEALTH_STAGE/medical_visits_new.csv
FILE_FORMAT = (FORMAT_NAME = HEALTH_DB.RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

SELECT *
FROM HEALTH_DB.RAW.MEDICAL_VISITS
WHERE visit_id IS NULL;

DELETE FROM HEALTH_DB.RAW.MEDICAL_VISITS
WHERE visit_id IS NULL;


SELECT * FROM RAW.MEDICAL_VISITS;



CREATE OR REPLACE TABLE HEALTH_DB.RAW.LAB_REPORTS (
    report_id STRING,
    migrant_id STRING,
    test_name STRING,
    test_result STRING,
    report_date DATE
);

truncate table HEALTH_DB.RAW.LAB_REPORTS;

COPY INTO HEALTH_DB.RAW.LAB_REPORTS
FROM @HEALTH_DB.RAW.HEALTH_STAGE/lab_reports.csv
FILE_FORMAT = (FORMAT_NAME = HEALTH_DB.RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';


SELECT * FROM RAW.LAB_REPORTS;

CREATE OR REPLACE TABLE HEALTH_DB.RAW.VACCINATION_RECORDS (
    record_id STRING,
    migrant_id STRING,
    vaccine_name STRING,
    dose_number INT,
    vaccination_date DATE
);

truncate table HEALTH_DB.RAW.VACCINATION_RECORDS;

COPY INTO HEALTH_DB.RAW.VACCINATION_RECORDS
FROM @HEALTH_DB.RAW.HEALTH_STAGE/vaccination_records.csv
FILE_FORMAT = (FORMAT_NAME = HEALTH_DB.RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';


SELECT * FROM RAW.VACCINATION_RECORDS;



CREATE OR REPLACE STREAM HEALTH_DB.RAW.STREAM_MIGRANT_PROFILES
ON TABLE HEALTH_DB.RAW.MIGRANT_PROFILES
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM HEALTH_DB.RAW.STREAM_MEDICAL_VISITS
ON TABLE HEALTH_DB.RAW.MEDICAL_VISITS
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM HEALTH_DB.RAW.STREAM_LAB_REPORTS
ON TABLE HEALTH_DB.RAW.LAB_REPORTS
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM HEALTH_DB.RAW.STREAM_VACCINATION_RECORDS
ON TABLE HEALTH_DB.RAW.VACCINATION_RECORDS
SHOW_INITIAL_ROWS = TRUE;


SELECT COUNT(*) FROM HEALTH_DB.RAW.STREAM_MIGRANT_PROFILES;
SELECT COUNT(*) FROM HEALTH_DB.RAW.STREAM_MEDICAL_VISITS;
SELECT COUNT(*) FROM HEALTH_DB.RAW.STREAM_LAB_REPORTS;
SELECT COUNT(*) FROM HEALTH_DB.RAW.STREAM_VACCINATION_RECORDS;










--if unexpectedly click create or replace table again
DROP STREAM IF EXISTS HEALTH_DB.RAW.STREAM_LAB_REPORTS;

CREATE OR REPLACE STREAM HEALTH_DB.RAW.STREAM_LAB_REPORTS
ON TABLE HEALTH_DB.RAW.LAB_REPORTS
SHOW_INITIAL_ROWS = TRUE;








