CREATE OR REPLACE DATABASE HEALTH_DB;

CREATE OR REPLACE SCHEMA HEALTH_DB.RAW;
CREATE OR REPLACE SCHEMA HEALTH_DB.STAGING;
CREATE OR REPLACE SCHEMA HEALTH_DB.CURATED;
CREATE OR REPLACE SCHEMA HEALTH_DB.ANALYTICS;


CREATE OR REPLACE ROLE HEALTH_ADMIN;
CREATE OR REPLACE ROLE HOSPITAL_USER;
CREATE OR REPLACE ROLE HEALTH_OFFICIAL;
CREATE OR REPLACE ROLE STATE_ANALYST;
CREATE OR REPLACE ROLE AUDITOR_ROLE;



CREATE OR REPLACE WAREHOUSE PIPELINE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


