GRANT USAGE ON DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;

GRANT ALL PRIVILEGES ON ALL TASKS IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;

-- Future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE HEALTH_DB TO ROLE HEALTH_ADMIN;






GRANT USAGE ON DATABASE HEALTH_DB TO ROLE HOSPITAL_USER;
GRANT USAGE ON SCHEMA HEALTH_DB.CURATED TO ROLE HOSPITAL_USER;

GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTH_DB.CURATED TO ROLE HOSPITAL_USER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTH_DB.CURATED TO ROLE HOSPITAL_USER;






GRANT USAGE ON DATABASE HEALTH_DB TO ROLE HEALTH_OFFICIAL;

GRANT USAGE ON SCHEMA HEALTH_DB.ANALYTICS TO ROLE HEALTH_OFFICIAL;

GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTH_DB.ANALYTICS TO ROLE HEALTH_OFFICIAL;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTH_DB.ANALYTICS TO ROLE HEALTH_OFFICIAL;





GRANT USAGE ON DATABASE HEALTH_DB TO ROLE STATE_ANALYST;
GRANT USAGE ON SCHEMA HEALTH_DB.ANALYTICS TO ROLE STATE_ANALYST;

GRANT SELECT ON ANALYTICS.VW_TOTAL_MIGRANTS TO ROLE STATE_ANALYST;
GRANT SELECT ON ANALYTICS.VW_DISEASE_TRENDS TO ROLE STATE_ANALYST;
GRANT SELECT ON ANALYTICS.VW_VACCINATION_COVERAGE TO ROLE STATE_ANALYST;
GRANT SELECT ON ANALYTICS.VW_STATE_HEALTH_RISK TO ROLE STATE_ANALYST;




GRANT USAGE ON DATABASE HEALTH_DB TO ROLE AUDITOR_ROLE;
GRANT USAGE ON SCHEMA HEALTH_DB.CURATED TO ROLE AUDITOR_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA HEALTH_DB.CURATED TO ROLE AUDITOR_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTH_DB.CURATED TO ROLE AUDITOR_ROLE;
